# Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY websocketserver/*.csproj websocketserver/
RUN dotnet restore websocketserver/websocketserver.csproj

COPY . .
WORKDIR /src/websocketserver

RUN dotnet publish -c Release -o /app/publish

# Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", "websocketserver.dll"]